# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9044518e163128c920acfebaf486514866be53f95df30c5d4fc3900a56d8033fe7841801b0dfd8f698a4f36715c9afb0dc916329abe93d6cc84a1b095692c1d6

test:
  secret_key_base: af82f5a6adbb55be2811ec96ed0f13a78a305f687f65a5665240f30a0003078b35ba54ded0a0cc93f19da5d5de6ecc888f38082efb35c426864752e23130cb3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
